{% set name = "colourtime" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colourtime-{{ version }}.tar.gz
  sha256: 3e1fe99c541dea22cd75467e0385e58551be4df953f073dcc4be2954338934b0

build:
  entry_points:
    - colourtime = colourtime:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.14,<0.15                # [build_platform != target_platform]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python
    - event-stream
    - matplotlib-base
    - numpy
    - pillow

test:
  imports:
    - colourtime
  commands:
    - pip check
    - colourtime --help
  requires:
    - pip

about:
  summary: Represent time with colours
  home: https://github.com/neuromorphicsystems/colourtime
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - Tobias-Fischer
